config/routes.rb
Ficheros::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "fichas#new", :as => "sign_up"
  root :to => "sessions#new"
  resources :sessions         
  resources :cargos    
  resources :fichas 
  
  match(
  "asistencias/:id" => "asistencias#destroy",
  :as => :eliminar_asistencia,
  :via => :delete
  )

  resources :asistencias

  resources :locals
  resources :lugars
  resources :actividads
  resources :examens
  resources :tipos
  resources :pagos
  resources :eventos
  resources :participacions

end

app/models/actividad.rb
class Actividad < ActiveRecord::Base
  attr_accessible :nombre, :descripcion  

  validates :nombre, :presence => true
  validates :nombre, :uniqueness => { :message => "Ya existe." }

  has_many :fichas
end 

app/models/asistencia.rb
class Asistencia < ActiveRecord::Base
  attr_accessible :fecha, :ficha_id, :horas,:mes_ano

  	validates :ficha_id, :presence => true
    belongs_to :ficha 

    def self.search(search)
    if search
      where('nombre LIKE ?', "%#{search}%")
    else
      scoped
    end
  end  




end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
  attr_accessible :descripcion, :nombre
  has_many :users
end

app/models/evento.rb
class Evento < ActiveRecord::Base
  attr_accessible :fecha, :nombre, :descripcion

  validates :nombre, :uniqueness => { :message => "Ya existe." }


  	validates :nombre, :presence => true
  has_many :participacions
end

app/models/examen.rb
class Examen < ActiveRecord::Base
  attr_accessible :fecha, :ficha_id, :detalle, :pagado
  validates :ficha_id, :presence => true
  belongs_to :ficha 
end

app/models/ficha.rb
class Ficha < ActiveRecord::Base
  attr_accessible :fechanacimiento, :local_id, :nombre, :rut , :photo, :tipo_id,:lugar_id, :actividad_id, :correo,:fono, :password, :password_confirmation,:cargo_id,:email


  attr_accessor :password
  before_save :encrypt_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  validates :rut, :actividad_id,:nombre,:cargo_id, :local_id, :fechanacimiento,:presence => true
  validates :nombre, :length => { :minimum => 2 }
  validates :rut, :uniqueness => { :message => "El rut existe" }
  validates :rut, :length => { :maximum => 12 }
  has_attached_file :photo,
                :path => ":rails_root/public/photo_attachment/:id/:style/:basename.:extension",
                :url => "/photo_attachment/:id/:style/:basename.:extension"

  validates_attachment_content_type :photo, :content_type => %w(image/jpeg image/jpg image/png)
  validates_attachment :photo,:size => { :in => 0..2150.kilobytes } 
  has_many :asistencias, :dependent => :delete_all
  belongs_to :cargo 



  def self.search(search)
    if search
      where('nombre LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

  def self.authenticate(email, password)
    ficha = find_by_email(email)
    if ficha && ficha.password_hash == BCrypt::Engine.hash_secret(password, ficha.password_salt)
      ficha
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/models/local.rb
class Local < ActiveRecord::Base
  attr_accessible :fono, :nombre, :ubicacion

  validates :nombre, :uniqueness => { :message => "El nombre existe" }
  
  validates :nombre, :presence => true
  has_many :fichas

end

app/models/lugar.rb
class Lugar < ActiveRecord::Base
  attr_accessible :nombre, :ubicacion
validates :nombre, :uniqueness => { :message => "Ya existe." }

    validates :nombre, :presence => true
  has_many :fichas
end 

app/models/pago.rb
class Pago < ActiveRecord::Base
  	attr_accessible :fecha, :ficha_id, :detalle, :valor,:mes_ano,:recibo, :tipo_id

    validates :valor, :tipo_id, :presence => true
    validates :ficha_id, :presence => true
	  has_attached_file :recibo
  	validates_attachment_content_type :recibo, :content_type => %w(image/jpeg image/jpg image/png)
  	validates_attachment :recibo,:size => { :in => 0..2150.kilobytes } 


  	belongs_to :tipo 
    belongs_to :ficha 


      def self.search(search)
    if search
      where('nombre LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end

app/models/participacion.rb
  	class Participacion < ActiveRecord::Base
  attr_accessible :ficha_id, :detalle , :evento_id,:fecha
  validates :evento_id, :presence => true
  validates :ficha_id, :presence => true
  belongs_to :evento 
  belongs_to :ficha
end

app/models/tipo.rb
class Tipo < ActiveRecord::Base
  attr_accessible :descripcion, :nombre
  validates :nombre, :uniqueness => { :message => "Ya existe." }

  validates :nombre, :presence => true
  has_many :pagos
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation,:ficha_id,:cargo_id
  
  attr_accessor :password
  before_save :encrypt_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  belongs_to :ficha 
  belongs_to :cargo 
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/examens_controller.rb
class ExamensController < ApplicationController
  def index  
    @examens = Examen.all
  end  

  def show
    if current_user
      if current_user.cargo_id == 2
        @examens = Examen.where(ficha_id: current_user)   
        @ficha = Ficha.find(current_user)    
      else
        @examens = Examen.where(ficha_id: params[:id])
        @ficha = Ficha.find(params[:id])
      end
    @examens = @examens.all(:order => "fecha DESC")

    /@examen = Examen.find(params[:id])/
        else
      redirect_to root_path, :notice => "Debe iniciar sesión."
    end

  end
  
  def new
    @examen = Examen.new
  end

  def create
    @examen = Examen.new(params[:examen])






    if @examen.save
      redirect_to examens_path, :notice => "Tu examen se ha salvado"
    else
      render "new"
    end
  end
  
  def edit
    @examen = Examen.find(params[:id])
  end

  def update
    @examen = Examen.find(params[:id])
  
  if @examen.update_attributes(params[:examen]) 
    redirect_to examens_path, :notice => "Tu examen se ha actualizado"
  else
    render "edit"
  end
end

  def destroy
    @examen = Examen.find(params[:id])
    @examen.destroy
    redirect_to examens_path, :notice => "Tu examen se ha borrado"
  end     
end

app/helpers/actividads_helper.rb
module ActividadsHelper
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/examens_helper.rb
module ExamensHelper
end

app/helpers/fichas_helper.rb
module FichasHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/lugars_helper.rb
module LugarsHelper
end

app/helpers/pagos_helper.rb
module PagosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/examens/edit.html - copia.erb
<div id="fullConten">

<div id="titulo", class="colorCeleste">Editar Examen</div>
<div id="texto2">
<%= simple_form_for @examen, :url => examen_path(@examen) , :method => 'put' do |f| %>
	<%= f.input :ficha_id, :collection => Ficha.all(:order=>'nombre'), :selected => :nombre,:label_method=> :nombre%>	
	<%= f.input :fecha, as: :date, start_year: Date.today.year+1,:use_month_numbers => true, end_year: Date.today.year-110, order: [:day,:month, :year]%>
	<label>Pagado :</label> 
	<%= f.select :pagado, [ 'Si', 'No']%>
	<%= f.input :detalle,:placeholder => 'Ingrese un detalle, grado u otro dato relevante.', input_html: { maxlength: 150, pattern:"[A-Z a-z]{2,25}" }%>
    
	



<%= f.submit "Agregar Nuevo Examen" ,:id => "botonIzq",:class=>"colorCeleste"%> 
<%= link_to "Cancelar", examens_path , :confirm => "¿Volver?",:id => "botonIzq",:class=>"colorCeleste"   %>
<% end %>
</div></div>

app/views/examens/edit.html.erb
<div id="fullConten">

<div id="titulo", class="colorCeleste">Editar Examen</div>
<div id="texto2">
<%= simple_form_for @examen, :url => examen_path(@examen) , :method => 'put' do |f| %>
	<%= f.input :ficha_id, label: 'Nombre',:collection => Ficha.all(:order=>'nombre'),:label_method=> :nombre, :include_blank => 'Seleccione'%>	

	<%= f.input :fecha, as: :date, start_year: Date.today.year+1,:use_month_numbers => true, end_year: Date.today.year-110, order: [:day,:month, :year]%>
	<label>Pagado :</label> 
	<%= f.select :pagado, [ 'Si', 'No']%>
	<%= f.input :detalle,:placeholder => 'Ingrese un detalle, grado u otro dato relevante.', input_html: { maxlength: 150, pattern:"[A-Z a-z]{2,25}" }%>

<%= f.submit "Guardar Cambios" ,:id => "botonIzq",:class=>"colorCeleste"%> 
<%= link_to "Cancelar", examens_path , :confirm => "¿Volver?",:id => "botonIzq",:class=>"colorCeleste"   %>
<% end %>
</div></div>

app/views/examens/index.html.erb
<h1>Examenes</h1>

<table id="contenPost">   
  
  
  <th id = "botonCeleste" ><%=  "Nombre"  %></th>  
  <th id = "botonCeleste" ><%=  "fecha" %></th>  
  <th id = "botonCeleste" ><%=  "Detalle" %></th>  
  <th id = "botonCeleste" style="width: 90px;"><%=  "Pagado" %></th>  
  
  
  <% for examen in @examens %>  
  <tr >      	


    <td><%=link_to Ficha.find_by_id(examen.ficha_id).nombre ,examen_path(examen)%></td>
    <td><%=link_to  examen.fecha , examen_path(examen)%></td>  
    <td><%=link_to examen.detalle , examen_path(examen)%></td> 
    <td><%=link_to examen.pagado , examen_path(examen)%></td> 
    <td><%= link_to "Editar", edit_examen_path(examen)  ,:id => "botonIzq",:class=>"colorCeleste"%>
    <%=  button_to "Borrar",  examen_path(examen), :confirm => "Perderá los datos. ¿Estas seguro?", :method => :delete ,:id => "botonIzq" ,:class=>"colorCeleste"%></td>



  </tr>  
  <% end %>  
</table>  
  
<%= link_to "Agregar un nuevo examen", new_examen_path  ,:id => "botonIzq" ,:class=>"colorCeleste"%> 
<%= link_to "Volver a Registro", fichas_path,:id => "botonIzq",:class=>"colorCeleste"   %>

app/views/examens/show.html - copia.erb
<div id="fullConten">
<div id="titulo", class="colorCeleste"> Examen de :<%= @ficha.nombre %></div>

<div id="texto2">
<p >Fecha : <%= @examen.fecha%></p>
<p >Pagado : <%= @examen.pagado%></p>
<p >Descripcion : <%= @examen.detalle%></p>


<%= link_to "Editar", edit_examen_path(@examen)  ,:id => "botonIzq",:class=>"colorCeleste"%>
<%= link_to "Volver", examens_path ,:id => "botonIzq",:class=>"colorCeleste"%>


</div>
</div>

app/views/examens/show.html.erb
<div id="full">
<h1>Examen de :<%= @ficha.nombre %></h1>


<table id="contenPost">   
  
  <th id = "botonCeleste" style="width: 110px;"><%=  "Fecha" %></th>  
  <th id = "botonCeleste" ><%=  "Detalle" %></th> 
  <th id = "botonCeleste" style="width: 110px;"><%=  "Pagado" %></th>   
  <th style="width: 110px;"></th>
  
  
  <% for examen in @examens %>  
  <tr >      	

    <td ><%=  examen.fecha%></td>  
    <td><%= examen.detalle %></td> 
    <td><%= examen.pagado %></td> 
    <td><div id="opciones">  
    
<%= link_to "Editar", edit_examen_path(examen)  ,:id => "botonIzq",:class=>"colorCeleste"%>

  <% if @current_user.cargo_id==1 %>
    <%=  link_to "Borrar",  examen_path(examen), :confirm => "Perderá los datos. ¿Estas seguro?", :method => :delete ,:id => "botonIzq" ,:class=>"colorCeleste"%>
  <% else %>   
  <% end %>

    </div>  </td> 

  </tr>  
  <% end %>  
</table>  
  
<%= link_to "Agregar nueva examen", new_examen_path  ,:id => "botonIzq" ,:class=>"colorCeleste"%>
<INPUT id = "botonIzq" class="colorCeleste" Type="button" VALUE="Volver"  onClick="history.go(-1);return true;">
</INPUT>
</div>