config/routes.rb
Ficheros::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "fichas#new", :as => "sign_up"
  root :to => "sessions#new"
  resources :sessions         
  resources :cargos    
  resources :fichas 
  
  match(
  "asistencias/:id" => "asistencias#destroy",
  :as => :eliminar_asistencia,
  :via => :delete
  )

  resources :asistencias

  resources :locals
  resources :lugars
  resources :actividads
  resources :examens
  resources :tipos
  resources :pagos
  resources :eventos
  resources :participacions

end

app/models/actividad.rb
class Actividad < ActiveRecord::Base
  attr_accessible :nombre, :descripcion  

  validates :nombre, :presence => true
  validates :nombre, :uniqueness => { :message => "Ya existe." }

  has_many :fichas
end 

app/models/asistencia.rb
class Asistencia < ActiveRecord::Base
  attr_accessible :fecha, :ficha_id, :horas,:mes_ano

  	validates :ficha_id, :presence => true
    belongs_to :ficha 

    def self.search(search)
    if search
      where('nombre LIKE ?', "%#{search}%")
    else
      scoped
    end
  end  




end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
  attr_accessible :descripcion, :nombre
  has_many :users
end

app/models/evento.rb
class Evento < ActiveRecord::Base
  attr_accessible :fecha, :nombre, :descripcion

  validates :nombre, :uniqueness => { :message => "Ya existe." }


  	validates :nombre, :presence => true
  has_many :participacions
end

app/models/examen.rb
class Examen < ActiveRecord::Base
  attr_accessible :fecha, :ficha_id, :detalle, :pagado
  validates :ficha_id, :presence => true
  belongs_to :ficha 
end

app/models/ficha.rb
class Ficha < ActiveRecord::Base
  attr_accessible :fechanacimiento, :local_id, :nombre, :rut , :photo, :tipo_id,:lugar_id, :actividad_id, :correo,:fono, :password, :password_confirmation,:cargo_id,:email


  attr_accessor :password
  before_save :encrypt_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  validates :rut, :actividad_id,:nombre,:cargo_id, :local_id, :fechanacimiento,:presence => true
  validates :nombre, :length => { :minimum => 2 }
  validates :rut, :uniqueness => { :message => "El rut existe" }
  validates :rut, :length => { :maximum => 12 }
  has_attached_file :photo,
                :path => ":rails_root/public/photo_attachment/:id/:style/:basename.:extension",
                :url => "/photo_attachment/:id/:style/:basename.:extension"

  validates_attachment_content_type :photo, :content_type => %w(image/jpeg image/jpg image/png)
  validates_attachment :photo,:size => { :in => 0..2150.kilobytes } 
  has_many :asistencias, :dependent => :delete_all
  belongs_to :cargo 



  def self.search(search)
    if search
      where('nombre LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

  def self.authenticate(email, password)
    ficha = find_by_email(email)
    if ficha && ficha.password_hash == BCrypt::Engine.hash_secret(password, ficha.password_salt)
      ficha
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/models/local.rb
class Local < ActiveRecord::Base
  attr_accessible :fono, :nombre, :ubicacion

  validates :nombre, :uniqueness => { :message => "El nombre existe" }
  
  validates :nombre, :presence => true
  has_many :fichas

end

app/models/lugar.rb
class Lugar < ActiveRecord::Base
  attr_accessible :nombre, :ubicacion
validates :nombre, :uniqueness => { :message => "Ya existe." }

    validates :nombre, :presence => true
  has_many :fichas
end 

app/models/pago.rb
class Pago < ActiveRecord::Base
  	attr_accessible :fecha, :ficha_id, :detalle, :valor,:mes_ano,:recibo, :tipo_id

    validates :valor, :tipo_id, :presence => true
    validates :ficha_id, :presence => true
	  has_attached_file :recibo
  	validates_attachment_content_type :recibo, :content_type => %w(image/jpeg image/jpg image/png)
  	validates_attachment :recibo,:size => { :in => 0..2150.kilobytes } 


  	belongs_to :tipo 
    belongs_to :ficha 


      def self.search(search)
    if search
      where('nombre LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end

app/models/participacion.rb
  	class Participacion < ActiveRecord::Base
  attr_accessible :ficha_id, :detalle , :evento_id,:fecha
  validates :evento_id, :presence => true
  validates :ficha_id, :presence => true
  belongs_to :evento 
  belongs_to :ficha
end

app/models/tipo.rb
class Tipo < ActiveRecord::Base
  attr_accessible :descripcion, :nombre
  validates :nombre, :uniqueness => { :message => "Ya existe." }

  validates :nombre, :presence => true
  has_many :pagos
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation,:ficha_id,:cargo_id
  
  attr_accessor :password
  before_save :encrypt_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  belongs_to :ficha 
  belongs_to :cargo 
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/helpers/actividads_helper.rb
module ActividadsHelper
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/examens_helper.rb
module ExamensHelper
end

app/helpers/fichas_helper.rb
module FichasHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/lugars_helper.rb
module LugarsHelper
end

app/helpers/pagos_helper.rb
module PagosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/eventos/index.html.erb
<h1>Todos los Eventos</h1>

<table id="contenPost">   
  
  
  <th id = "botonCeleste" ><%=  "Nombre"  %></th>  
    <th id = "botonCeleste" style="width: 110px;" ><%=  "Fecha"  %></th>  
  <th id = "botonCeleste" ><%=  "Descripción" %></th>  
  <th ></th> 
  
  <% for evento in @eventos %>  
  <tr >      
  

    <td ><%= link_to evento.nombre, evento %></td>  
    <td ><%= link_to evento.fecha, evento %></td>
    <td ><%= link_to evento.descripcion, evento %></td>    

    
  <td><div id="opciones">  <%= link_to "Editar", edit_evento_path(evento) , id:"botonIzq"					,:class=>"colorCeleste"%>
					 <%=  button_to "Borrar", evento, :confirm => "Perderá los datos. ¿Estas seguro?", :method => :delete ,:id => "botonIzq" ,:class=>"colorCeleste"%>
	</div></td> 

</tr>
  <% end %>  
</table>  
  
<%= link_to "Agregar Nuevo Evento", new_evento_path  ,:id => "botonIzq" ,:class=>"colorCeleste"%> 
<%= link_to "Volver a Registro", fichas_path,:id => "botonIzq",:class=>"colorCeleste"   %>

app/views/lugars/index.html.erb
<div id="full">

<h1>Lugares de Entrenamiento</h1>

<table id="contenPost">   
  
  
  <th id = "botonCeleste" ><%=  "Nombre"  %></th>  
  <th id = "botonCeleste" ><%=  "Dirección" %></th>  
  <th style="width: 110px;"></th> 
  
  <% for lugar in @lugars %>  
  <tr >      	
    <td ><%= link_to lugar.nombre ,lugar%></td>  
    <td ><%= link_to lugar.ubicacion ,lugar%></td>  
<td><div id="opciones"><%= link_to "Editar", edit_lugar_path(lugar)  ,:id => "botonIzq",:class=>"colorCeleste"%>
    <%=  button_to "Borrar",  lugar_path(lugar), :confirm => "Perderá los datos. ¿Estas seguro?", :method => :delete ,:id => "botonIzq" ,:class=>"colorCeleste"%></td>
  </div></td>  
  <% end %>  
</table>  
  
<%= link_to "Agregar Nuevo lugar", new_lugar_path  ,:id => "botonIzq" ,:class=>"colorCeleste"%> 
<%= link_to "Volver a Registro", fichas_path,:id => "botonIzq",:class=>"colorCeleste"   %>

</div>

app/views/pagos/edit.html.erb
<div id="fullConten">

<div id="titulo", class="colorCeleste">Editar Pago</div>
<div id="texto2">
<%= simple_form_for @pago do |f| %>
<% if @pago.errors.any? %>
	<div id="flashmsg"> 
			
		<ul>Errores:
			<% @pago.errors.full_messages.each do |message| %>
				<li><%= message %></li>				
			<% end %>
		</ul></div>
	<% end %>
	
<% if current_user.cargo_id == 1 %>
	<%= f.input :ficha_id, :collection => Ficha.all(:order=>'nombre'),:label_method=> :nombre, :include_blank => 'Seleccione'%>			

<% else %>			
<% end %>

	<%= f.input :fecha, as: :date, start_year: Date.today.year,:use_month_numbers => true, end_year: Date.today.year-110, order: [:day,:month, :year]%>

	<%= f.input :valor,:required => true,as: :integer, input_html: { maxlength: 10, min:"1"}  %>
	<%= f.input :detalle,:placeholder => 'Ingrese Detalle del Cobro Se es Necesario', input_html: { maxlength: 150, pattern:"[A-Z a-z]{2,25}" }%>   
	


<%= f.submit "Guardar Cambios" ,:id => "botonIzq",:class=>"colorCeleste"%> 
<%= link_to "Cancelar", pagos_path , :confirm => "¿Volver?",:id => "botonIzq",:class=>"colorCeleste"   %>
<% end %>
</div></div>

app/views/pagos/index.html.erb
<div id="full">

<h1>Todos los Pagos</h1>

<table id="contenPost">   

  <th id = "botonCeleste" ><%= sortable "ficha_id"  %></th>  
  <th id = "botonCeleste" style="width: 110px;"><%= sortable "fecha" %></th>
  <th id = "botonCeleste" ><%= sortable "valor" %></th>
  <th style="width: 110px;"></th>
  
  <% for pago in @pagos %>  
  <tr >  

    <td>

    <%=
if Ficha.find_by_id(pago.ficha_id.to_i).nil? ;  
  'Sin Información';
else link_to Ficha.find_by_id(pago.ficha_id.to_i).nombre, Ficha.find_by_id(pago.ficha_id.to_i);
end    %>
    </td>
    <td ><%=  pago.fecha%></td>  

    
    <td><%= number_to_currency(pago.valor, :unit => "$", :delimiter => ".", :precision=> 0) %></td> 





<td><div id="opciones"><%= link_to "Editar", edit_pago_path(pago)  ,:id => "botonIzq",:class=>"colorCeleste"%>
    <%= button_to "Borrar",  pago_path(pago), :confirm => "Perderá los datos. ¿Estas seguro?", :method => :delete ,:id => "botonIzq" ,:class=>"colorCeleste"%>  



</div></td>

  </tr>  
  <% end %>  
</table>  


  <%= will_paginate @pagos %>  
  
<%= link_to "Agregar Nuevo Pago", new_pago_path  ,:id => "botonIzq" ,:class=>"colorCeleste"%> 

<%= link_to "Volver a Registro", fichas_path,:id => "botonIzq",:class=>"colorCeleste"   %>


</div>

app/views/pagos/new.html.erb
<div id="fullConten">

<div id="titulo", class="colorCeleste">Nuevo Pago</div>
<div id="texto2">
<%= simple_form_for @pago, :url => pagos_path , :method => 'post' do |f| %>


<% if @pago.errors.any? %>
	<div id="flashmsg"> 
			
		<ul>Errores:
			<% @pago.errors.full_messages.each do |message| %>
				<li><%= message %></li>				
			<% end %>
		</ul></div>
	<% end %>


<% if current_user.cargo_id == 1 %>
	<%= f.input :ficha_id, :collection => Ficha.all(:order=>'nombre'), :selected => :nombre,:label_method=> :nombre%>			

<% else %>			
<% end %>		


	

	<%= f.input :fecha, as: :date, start_year: Date.today.year,:use_month_numbers => true, end_year: Date.today.year-110, order: [:day,:month, :year]%>

	<%= f.input :valor, as: :integer ,:required => true,as: :integer, input_html: { maxlength: 10, min:"1", value:"0" , maxlength: 30, step: "any"}  %>


	<%= f.input :detalle,:placeholder => 'Ingrese Detalle del Cobro Se es Necesario', input_html: { maxlength: 150, pattern:"[A-Z a-z]{2,25}" }%>   




<%= f.submit "Agregar Nuevo Pago" ,:id => "botonIzq",:class=>"colorCeleste"%> 
<%= link_to "Cancelar", pagos_path , :confirm => "¿Volver?",:id => "botonIzq",:class=>"colorCeleste"   %>
<% end %>
</div></div>

app/views/tipos/index.html.erb
<div id="full">

<h1>Todos los Tipos de Pagos</h1>

<table id="contenPost">   
  
  
  <th id = "botonCeleste" >Nombre</th>  
  <th id = "botonCeleste" >Descripción</th>  
  <th style="width: 110px;"></th>

  
  <% for tipo in @tipos %>  
  <tr >      	
    <td ><%=link_to  tipo.nombre, tipo%></td>  
    <td ><%=link_to  tipo.descripcion, tipo%></td> 
        <td><div id="opciones">  <%= link_to "Editar", edit_tipo_path(tipo) , id:"botonIzq"					,:class=>"colorCeleste"%>
					 <%=  button_to "Borrar", tipo, :confirm => "Perderá los datos. ¿Estas seguro?", :method => :delete ,:id => "botonIzq" ,:class=>"colorCeleste"%>
	</div></td>  
  </tr>  



  <% end %>  
</table>  
  

<%= link_to "Agregar Nuevo Grado", new_tipo_path  ,:id => "botonIzq" ,:class=>"colorCeleste"%> 
<%= link_to "Volver a Registro", fichas_path,:id => "botonIzq",:class=>"colorCeleste"   %>

</div>