config/routes.rb
Ficheros::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "fichas#new", :as => "sign_up"
  root :to => "sessions#new"
  resources :sessions         
  resources :cargos    
  resources :fichas 
  
  match(
  "asistencias/:id" => "asistencias#destroy",
  :as => :eliminar_asistencia,
  :via => :delete
  )

  resources :asistencias

  resources :locals
  resources :lugars
  resources :actividads
  resources :examens
  resources :tipos
  resources :pagos
  resources :eventos
  resources :participacions

end

app/models/ficha.rb
class Ficha < ActiveRecord::Base
  attr_accessible :fechanacimiento, :local_id, :nombre, :rut , :photo, :tipo_id,:lugar_id, :actividad_id, :correo,:fono, :password, :password_confirmation,:cargo_id,:email


  attr_accessor :password
  before_save :encrypt_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  validates :rut, :actividad_id,:nombre,:cargo_id, :local_id, :fechanacimiento,:presence => true
  validates :nombre, :length => { :minimum => 2 }
  validates :rut, :uniqueness => { :message => "El rut existe" }
  validates :rut, :length => { :maximum => 12 }
  has_attached_file :photo,
                :path => ":rails_root/public/photo_attachment/:id/:style/:basename.:extension",
                :url => "/photo_attachment/:id/:style/:basename.:extension"

  validates_attachment_content_type :photo, :content_type => %w(image/jpeg image/jpg image/png)
  validates_attachment :photo,:size => { :in => 0..2150.kilobytes } 
  has_many :asistencias, :dependent => :delete_all
  belongs_to :cargo 



  def self.search(search)
    if search
      where('nombre LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

  def self.authenticate(email, password)
    ficha = find_by_email(email)
    if ficha && ficha.password_hash == BCrypt::Engine.hash_secret(password, ficha.password_salt)
      ficha
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/fichas_controller.rb
class FichasController < ApplicationController
 helper_method :sort_column, :sort_direction  
  def index  
    
    if current_user
      if current_user.cargo_id == 2
          redirect_to ficha_path (current_user)
        else
          @fichas = Ficha.search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 5, :page => params[:page])
        end      
      else
        redirect_to root_path, :notice => "Debe iniciar sesión."
    end

  end  

  def show
    if current_user 
      if current_user.cargo_id == 2
        @ficha = Ficha.find(current_user)        
      else
        @ficha = Ficha.find(params[:id])
      end

        @asistencias = Asistencia.where(ficha_id: @ficha.id)
        @pagos = Pago.where(ficha_id: @ficha.id)
        @participacionParcial = Participacion.where(ficha_id: @ficha.id)
        @examenParcial = Examen.where(ficha_id: @ficha.id)
        
        @local = Local.find_by_id(@ficha.local_id.to_i)
        @tipo = Tipo.find_by_id(@ficha.tipo_id.to_i)
        @cargo = Cargo.find_by_id(@ficha.cargo_id.to_i)
        @lugar = Lugar.find_by_id(@ficha.lugar_id.to_i)
        @actividad = Actividad.find_by_id(@ficha.actividad_id.to_i)
        @asistenciaParcial= @asistencias.select("date(mes_ano) as ordered_fecha, sum(horas) as total_horas").group("date(mes_ano)")
        @asistenciaParcial=@asistenciaParcial.where(mes_ano: (Time.now - 1.year)..Time.now)
        
        @pagoParcial= @pagos.select("date(mes_ano) as ordered_fecha, sum(valor) as total_horas").group("date(mes_ano)")
        @pagoParcial=@pagoParcial.where(mes_ano: (Time.now - 1.year)..Time.now)

        @participacionParcial=@participacionParcial.where(fecha: (Time.now - 1.year)..Time.now)
        @examenParcial=@examenParcial.where(fecha: (Time.now - 1.year)..Time.now)


    else
      redirect_to root_path, :notice => "Debe iniciar sesión."
    end
  end
  
  def new

    @ficha = Ficha.new
        
  end

  def create    
        @ficha = Ficha.new(params[:ficha])
        if current_user
          @ficha.cargo_id=2
        else
        end
        if @ficha.save
          redirect_to new_ficha_path, :notice => "Tu ficha se ha salvado"
        else
          render "new"
        end    
  end
  
  def edit
    if current_user
    @ficha = Ficha.find(params[:id])
        else
      redirect_to root_path, :notice => "Debe iniciar sesión."
    end
  end

  def update
    if current_user
    @ficha = Ficha.find(params[:id])
  
  if @ficha.update_attributes(params[:ficha]) 
    redirect_to fichas_path, :notice => "Tu ficha se ha actualizado"
  else
    render "edit"
  end
      else
      redirect_to root_path, :notice => "Debe iniciar sesión."
    end
end

  def destroy
    @ficha = Ficha.find(params[:id])

    if @ficha.id ==current_user.id
      session[:ficha_id] = nil
    else
  end




    @ficha.destroy
    redirect_to fichas_path, :notice => "Tu ficha se ha borrado"
  end 

    private  
def sort_column  
  Ficha.column_names.include?(params[:sort]) ? params[:sort] : "nombre"  
end  
    
def sort_direction  
  %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"  
end  
end

app/helpers/fichas_helper.rb
module FichasHelper
end

app/views/fichas/edit.html.erb
<div id="titulo", class="colorCeleste">Editar Ficha</div>
<%= simple_form_for @ficha do |f| %>

	<% if @ficha.errors.any? %>
		<h2>Errores:</h2>	
		<ul>
			<% @ficha.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
<div id="ficha">

	<% if current_user.cargo_id == 1 %>
	<div id="input"><%= f.input :nombre,:placeholder => 'Ingrese el nombre', input_html: { maxlength: 30, pattern:"[A-Z a-z]{2,25}" }%></div>
	<div id="input"><%= f.input :rut,:placeholder => 'Ingrese el rut', input_html: { maxlength: 12 }%></div>

	<div id="input"><%= f.input :cargo_id, label: 'Tipo de Usuario', :collection => Cargo.all(:order=>'nombre'),:label_method=> :nombre, :include_blank => 'Seleccione'%></div>	
	<% else %>			
	<% end %>
	
	<div id="input"><%= f.input :email,:placeholder => 'persona@servicio.com', input_html: { type:'email'  }%></div>

	<div id="input"><%= f.input :password%></div>

	<div id="input"><%= f.input :password_confirmation %></div>


	<div id="input"><%= f.input :fono, input_html: { maxlength: 15 }%></div>
	
	<div id="input"><%= f.input :fechanacimiento, label: 'Fecha de Nacimiento', as: :date, start_year: Date.today.year,:use_month_numbers => true, end_year: Date.today.year-110, order: [:day,:month, :year] ,:prompt => { :day => 'Dia', :month => 'Mes', :year => 'Año' }%></div>
	

	<div id="input"><%= f.input :actividad_id, :collection => Actividad.all(:order=>'nombre'), :label_method=> :nombre, :include_blank => 'Seleccione'%></div>

    <div id="input"><%= f.input :local_id, label: 'Lugar de estudio/trabajo', :collection => Local.all(:order=>'nombre'),:label_method=> :nombre, :include_blank => 'Seleccione'%></div>

    <div id="input"><%= f.label "Imagen (2 mb máx, jpg,jpeg,png)" ,:id=>"small"%>    
    <%= f.file_field :photo %></div>

 <div id="input">
<%= f.submit "Guardar Cambios" ,:id => "botonIzq",:class=>"colorCeleste"%> 


<%= link_to "Cancelar", fichas_path , :confirm => "¿Volver?",:id => "botonIzq",:class=>"colorCeleste"   %></div>
</div>
<% end %>

app/views/fichas/index.html.erb
<div id="full">
<h1> Registros </h1>  
<table id="contenPost">   
  
  <th style="width: 110px;"></th>
  <th id = "botonCeleste" ><%= sortable "nombre"  %></th>  
  <th id = "botonCeleste" style="width: 110px;"><%= sortable "rut" %></th>  

  <th style="width: 110px;"></th> 
  
  <% for ficha in @fichas %>  

  <tr >      
  <td><a  href="<%=ficha.photo.url%>"><%= image_tag ficha.photo.url ,:id=>"imagen2"%></a></td>
    <td ><%= link_to ficha.nombre, ficha %></td>  
    <td class="rut"><%= link_to ficha.rut, ficha%></td>      
      

    <td><div id="opciones">  <%= link_to "Editar", edit_ficha_path(ficha) , id:"botonIzq"         ,:class=>"colorCeleste"%>

      <%= button_to "Eliminar", ficha, :method => :delete, :confirm => "Perderá los datos. ¿Estas seguro?", :id => "botonIzq",:class=>"colorCeleste" %>

            
  </div></td>
  </tr>  
  <% end %>
</table>  

  <%= will_paginate @fichas %>  
  
<%= link_to "Agregar nueva ficha", new_ficha_path  ,:id => "botonIzq" ,:class=>"colorCeleste"%> 
</div>

app/views/fichas/new.html.erb
<div id="titulo", class="colorCeleste">Nueva ficha</div>
<%= simple_form_for @ficha, :url => fichas_path , :method => 'post' do |f| %>

	<% if @ficha.errors.any? %>
	<div id="flashmsg"> 
			
		<ul>Errores:
			<% @ficha.errors.full_messages.each do |message| %>
				<li><%= message %></li>				
			<% end %>
		</ul></div>
	<% end %>

<div id="ficha">

	<div id="input"><%= f.input :nombre,:placeholder => 'Ingrese el nombre', input_html: { maxlength: 30, pattern:"[A-Z a-z]{2,25}" }%></div>
	<div id="input"><%= f.input :rut,:placeholder => 'Con puntos y guión.', input_html: { maxlength: 12 }%></div>
	
	<div id="input"><%= f.input :email,:placeholder => 'persona@servicio.com', input_html: { type:'email'  }%></div>

	<div id="input"><%= f.input :password%></div>

	<div id="input"><%= f.input :password_confirmation %></div>




<% 


if current_user 
	if current_user.cargo_id == 1 %>
	  <div id="input"><%= f.input :cargo_id, label: 'Tipo de Usuario', :collection => Cargo.all(:order=>'nombre'), :include_blank => 'Seleccione',:label_method=> :nombre%></div>	
	<% else 
	 end
else%>
	 <%= f.hidden_field :cargo_id, :value => 2 %>
	
<%end %>	



  
	
	<div id="input"><%= f.input :fono, input_html: { maxlength: 15 }%></div>
	
	<div id="input"><%= f.input :fechanacimiento, label: 'Fecha de Nacimiento', as: :date, start_year: Date.today.year,:use_month_numbers => true, end_year: Date.today.year-110, order: [:day,:month, :year] ,:prompt => { :day => 'Dia', :month => 'Mes', :year => 'Año' }%></div>
	

	<div id="input"><%= f.input :actividad_id, :collection => Actividad.all(:order=>'nombre'),  :include_blank => 'Seleccione',:label_method=> :nombre%></div>

    <div id="input"><%= f.input :local_id, label: 'Lugar de estudio/trabajo', :collection => Local.all(:order=>'nombre'), :include_blank => 'Seleccione',:label_method=> :nombre%></div>

    <div id="input"><%= f.label "Imagen (2 mb máx, jpg,jpeg,png)" ,:id=>"small"%>    
    <%= f.file_field :photo %></div>




 <div id="input">
<%= f.submit "Agregar Nueva Ficha" ,:id => "botonIzq",:class=>"colorCeleste"%> 

<%= link_to "Cancelar", fichas_path , :confirm => "¿Volver?",:id => "botonIzq",:class=>"colorCeleste"   %></div>
</div>
<% end %>

app/views/fichas/show.html.erb
<div id="fullConten">
<div id="titulo", class="colorCeleste"> Nombre: <%=  @ficha.nombre %></div>

<div id="texto">
<a  href="<%=@ficha.photo.url%>"><%= image_tag @ficha.photo.url ,:id=>"imagen"%></a>


<p >ID: <%=@ficha.id.to_i%></p>
<p>Rut: <%=  @ficha.rut %></p>
 <p >Tipo: <%= 
if @cargo.nil? ;  'Sin Información';
else @cargo.nombre;
end  %></p>

<p> Fecha de Nacimiento: <%=  @ficha.fechanacimiento.to_formatted_s(:rfc822)      %></p>
<p >Actividad: <%= 
if @actividad.nil? ;  'Sin Información';
else @actividad.nombre;
end  %></p>



<p >Lugar de estudio/trabajo: <%= 
if @local.nil? ;  'Sin Información';
else @local.nombre;
end  %></p>

<p >Total Horas: <%=number_to_currency(   @asistencias.sum(:horas), :unit => "", :delimiter => ".", :precision=> 0)%></p>


<p>Total Pagos:<%= number_to_currency(@pagos.sum(:valor), :unit => "$", :delimiter => ".", :precision=> 0) %></p>


<p >Fono: <%=number_to_phone(@ficha.fono)%></p>
<p >Email: <%=@ficha.email%></p>

</div>
<p><%= link_to "Editar", edit_ficha_path(@ficha)  ,:id => "botonIzq",:class=>"colorCeleste"%>
<INPUT id = "botonIzq" class="colorCeleste" Type="button" VALUE="Volver"  onClick="history.go(-1);return true;">




  <table id="tableConten">




  <td ><h1>ASISTENCIA PARCIAL </h1>


 <%= link_to 'VER ASISTENCIA COMPLETA ', asistencia_path(@ficha)%>



<table id="tableConten">   
  
  <th id = "botonCeleste" ><%=  "Mes Año" %></th>  
  <th id = "botonCeleste" ><%=  "Horas Mensuales" %></th>  
  
  
  <% for asistencia in @asistenciaParcial %>  
  <tr >  
  <td><%= Time.zone.parse(asistencia.ordered_fecha).strftime("%Y" " %B") %></td>      
  <td><%= number_to_currency(asistencia.total_horas, :unit => "", :delimiter => ".", :precision=> 0) %></td>    

  </tr>  
  <% end %>  
</table> 
</table>



<table id="tableConten"><td ><h1>PAGOS PARCIALES</h1>
<table id="tableConten">   
   <%= link_to 'VER TODOS LOS PAGOS ', pago_path(@ficha)%>
  <th id = "botonCeleste" ><%=  "Mes Año" %></th>  
  <th id = "botonCeleste" ><%=  "Valor" %></th>  
  
  
  <% for pago in @pagoParcial %>  
  <tr >  
  <td><%= Time.zone.parse(pago.ordered_fecha).strftime("%Y" " %B") %></td>      
  <td><%= number_to_currency(pago.total_horas, :unit => "$", :delimiter => ".", :precision=> 0) %></td>    

  </tr>  
  <% end %>  
</table> 
</td></table>

<table id="tableConten"><td ><h1>PARTICIPACIONES RECIENTES</h1>
<table id="tableConten">   


  <%= link_to 'VER TODAS LAS PARTICIPACIONES ', participacion_path(@ficha)%>
  <th id = "botonCeleste" ><%=  "Nombre" %></th>
  <th id = "botonCeleste" ><%=  "Fecha" %></th>  
  <th id = "botonCeleste" ><%=  "Detalle" %></th>  
  
  
  <% for participacion in @participacionParcial %>  
  <tr >  
  <td ><%=  Evento.find_by_id(participacion.evento_id).nombre%></td>
  <td><%= participacion.fecha %></td>      
  <td><%= participacion.detalle %></td>   
  </tr>  
  <% end %>  
</table> 

</td></table>

<table id="tableConten"><td ><h1>EXAMENES RECIENTES</h1>
<table id="tableConten">   


  <%= link_to 'VER TODOS LOS EXAMENES ', examen_path(@ficha)%>

  <th id = "botonCeleste" ><%=  "Fecha" %></th>  
  <th id = "botonCeleste" ><%=  "Detalle" %></th>  
  <th id = "botonCeleste" ><%=  "Pagado" %></th>
  
  <% for examen in @examenParcial %>  
  <tr >  
  <td><%= examen.fecha %></td>      
  <td><%= examen.detalle %></td>
  <td ><%= examen.pagado%></td>   
  </tr>  
  <% end %>  
</table> 

</td></table>

</div>